# Generated by Django 4.2 on 2023-04-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_car_drivers_alter_driver_driver_licence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_licence',
            new_name='license_number',
        ),
    ]
